import { FrameworkType } from '@/types'
import type { FrameworkRuleSet } from '../ruleEngine'

export const whyTreeRules: FrameworkRuleSet = {
  framework: FrameworkType.WHY_TREE,
  rules: [
    {
      patterns: [
        'なぜ',
        'why',
        '問題は',
        '課題は',
        '下がっている',
        '低下している',
        '減っている',
        '落ちている',
        '悪化している',
        'できていない',
        '不足している',
        '遅れている',
        'うまくいっていない',
        '困っている',
        'が起きている',
        'が発生している',
      ],
      role: 'root',
      weight: 1.0,
    },
    {
      patterns: [
        '原因',
        '要因',
        '理由',
        'cause',
        'から',
        'ため',
        'せいで',
        'によって',
        'モチベーション',
        'やる気',
        '意欲',
        '仕組み',
        'ルール',
        '基準',
        'マニュアル',
        '標準',
        '優位性',
        '競争力',
        'コスト',
        '品質',
        '納期',
      ],
      role: 'branch',
      weight: 0.9,
    },
    {
      patterns: [
        '根本',
        '本質',
        'そもそも',
        '背景',
        '文化',
        '体制',
        '構造',
        '環境',
        '教育',
        '育成',
        'ノウハウ',
        '経験不足',
        '予算不足',
        'リソース不足',
        '人員不足',
      ],
      role: 'leaf',
      weight: 0.8,
    },
  ],
  defaultRole: 'branch',
  rootExtraction: (sentences) => sentences[0] ?? 'Root problem',
}
