import type { NodeRole } from './graph'

export type FrameworkCategory =
  | '論理構造'
  | '戦略分析'
  | '論理展開'
  | '業務改善'
  | '品質・論理'
  | 'プロジェクト管理'

export type FrameworkVisualization = 'tree' | 'matrix'

export const FrameworkType = {
  WHY_TREE: 'why-tree',
  WHAT_TREE: 'what-tree',
  HOW_TREE: 'how-tree',
  PYRAMID: 'pyramid',
  MECE: 'mece',
  THREE_C: 'three-c',
  SWOT: 'swot',
  PEST: 'pest',
  ANSOFF: 'ansoff',
  DEDUCTION: 'deduction',
  INDUCTION: 'induction',
  CROSS_SWOT: 'cross_swot',
  PRIORITY_MATRIX: 'priority_matrix',
  AS_IS_TO_BE: 'as_is_to_be',
  PHENOMENON_TO_ACTION: 'phenomenon_to_action',
  BUSINESS_FLOW: 'business_flow',
  ECRS: 'ecrs',
  FOUR_M: 'four_m',
  QCD: 'qcd',
  FISHBONE: 'fishbone',
  ISSUE_TREE: 'issue_tree',
  STP: 'stp',
  PPM: 'ppm',
  BSC: 'bsc',
  KPI: 'kpi',
  ABC: 'abc',
  RACI: 'raci',
  WBS: 'wbs',
  YWT: 'ywt',
  SPIN: 'spin',
  CUSTOMER_JOURNEY: 'customer_journey',
  VSM: 'vsm',
  DMAIC: 'dmaic',
} as const

export type FrameworkType = (typeof FrameworkType)[keyof typeof FrameworkType]

export interface FrameworkDefinition {
  type: FrameworkType
  icon: string
  label: string
  description: string
  category: FrameworkCategory
  visualization: FrameworkVisualization
  nodeRoles: NodeRole[]
}

export const FRAMEWORK_REGISTRY: Record<FrameworkType, FrameworkDefinition> = {
  [FrameworkType.WHY_TREE]: {
    type: FrameworkType.WHY_TREE,
    icon: '🔍',
    label: 'Whyツリー',
    description: '問題の根本原因を深掘りする',
    category: '論理構造',
    visualization: 'tree',
    nodeRoles: ['problem', 'cause', 'root-cause'],
  },
  [FrameworkType.WHAT_TREE]: {
    type: FrameworkType.WHAT_TREE,
    icon: '📋',
    label: 'Whatツリー',
    description: 'テーマを構成要素に分解する',
    category: '論理構造',
    visualization: 'tree',
    nodeRoles: ['theme', 'element', 'fact', 'definition'],
  },
  [FrameworkType.HOW_TREE]: {
    type: FrameworkType.HOW_TREE,
    icon: '🪜',
    label: 'Howツリー',
    description: '目標達成の手段・施策を展開する',
    category: '論理構造',
    visualization: 'tree',
    nodeRoles: ['goal', 'approach', 'action', 'resource'],
  },
  [FrameworkType.PYRAMID]: {
    type: FrameworkType.PYRAMID,
    icon: '△',
    label: 'ピラミッド',
    description: '結論を根拠・事実で支える',
    category: '論理展開',
    visualization: 'tree',
    nodeRoles: ['conclusion', 'argument', 'evidence'],
  },
  [FrameworkType.MECE]: {
    type: FrameworkType.MECE,
    icon: '✓',
    label: 'MECE確認',
    description: '漏れ・重複なく情報を整理する',
    category: '論理構造',
    visualization: 'tree',
    nodeRoles: ['root', 'branch', 'leaf', 'category', 'segment', 'overlap', 'gap'],
  },
  [FrameworkType.THREE_C]: {
    type: FrameworkType.THREE_C,
    icon: '3C',
    label: '3C分析',
    description: '顧客・競合・自社を整理する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['customer', 'competitor', 'company'],
  },
  [FrameworkType.SWOT]: {
    type: FrameworkType.SWOT,
    icon: '⚡',
    label: 'SWOT分析',
    description: '強み・弱み・機会・脅威を整理する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['strength', 'weakness', 'opportunity', 'threat'],
  },
  [FrameworkType.PEST]: {
    type: FrameworkType.PEST,
    icon: '🌍',
    label: 'PEST分析',
    description: '政治・経済・社会・技術を分析する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['political', 'economic', 'social', 'technological'],
  },
  [FrameworkType.ANSOFF]: {
    type: FrameworkType.ANSOFF,
    icon: '📈',
    label: 'アンゾフマトリクス',
    description: '市場×製品で成長戦略を考える',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['market-penetration', 'market-development', 'product-development', 'diversification'],
  },
  [FrameworkType.DEDUCTION]: {
    type: FrameworkType.DEDUCTION,
    icon: '→',
    label: '演繹法',
    description: '大前提→小前提→結論で論理を展開する',
    category: '論理展開',
    visualization: 'tree',
    nodeRoles: ['major_premise', 'minor_premise', 'conclusion'],
  },
  [FrameworkType.INDUCTION]: {
    type: FrameworkType.INDUCTION,
    icon: '←',
    label: '帰納法',
    description: '複数の事実から一般則を導く',
    category: '論理展開',
    visualization: 'tree',
    nodeRoles: ['observation', 'pattern', 'generalization'],
  },
  [FrameworkType.CROSS_SWOT]: {
    type: FrameworkType.CROSS_SWOT,
    icon: '✕',
    label: 'クロスSWOT',
    description: 'SWOTを掛け合わせて戦略を策定する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['so_strategy', 'wo_strategy', 'st_strategy', 'wt_strategy'],
  },
  [FrameworkType.PRIORITY_MATRIX]: {
    type: FrameworkType.PRIORITY_MATRIX,
    icon: '⭐',
    label: '優先順位マトリクス',
    description: '効果×実行しやすさで施策を優先順位付けする',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['high_impact_easy', 'high_impact_hard', 'low_impact_easy', 'low_impact_hard'],
  },
  [FrameworkType.AS_IS_TO_BE]: {
    type: FrameworkType.AS_IS_TO_BE,
    icon: '⟹',
    label: 'As-Is/To-Be/Gap',
    description: '現状・理想・差分・打ち手を整理する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['as_is', 'to_be', 'gap', 'action'],
  },
  [FrameworkType.PHENOMENON_TO_ACTION]: {
    type: FrameworkType.PHENOMENON_TO_ACTION,
    icon: '🔧',
    label: '現象→課題→施策',
    description: '現象・問題・原因・課題・施策の5段階で整理する',
    category: '業務改善',
    visualization: 'tree',
    nodeRoles: ['phenomenon', 'problem', 'cause', 'issue', 'measure'],
  },
  [FrameworkType.BUSINESS_FLOW]: {
    type: FrameworkType.BUSINESS_FLOW,
    icon: '🔁',
    label: '業務フロー分析',
    description: '入力→処理→判断→出力→保管→共有で業務を分解する',
    category: '業務改善',
    visualization: 'matrix',
    nodeRoles: ['flow_input', 'flow_process', 'flow_decision', 'flow_output', 'flow_storage', 'flow_share'],
  },
  [FrameworkType.ECRS]: {
    type: FrameworkType.ECRS,
    icon: '⚙️',
    label: 'ECRS分析',
    description: 'なくす・まとめる・順番変更・簡単にで業務改善する',
    category: '業務改善',
    visualization: 'matrix',
    nodeRoles: ['eliminate', 'combine', 'rearrange', 'simplify'],
  },
  [FrameworkType.FOUR_M]: {
    type: FrameworkType.FOUR_M,
    icon: '4M',
    label: '4M分析',
    description: 'Man・Machine・Material・Methodで原因を分類する',
    category: '品質・論理',
    visualization: 'matrix',
    nodeRoles: ['man', 'machine', 'material', 'method'],
  },
  [FrameworkType.QCD]: {
    type: FrameworkType.QCD,
    icon: 'QCD',
    label: 'QCD分析',
    description: 'Quality・Cost・Deliveryで効果を整理する',
    category: '品質・論理',
    visualization: 'matrix',
    nodeRoles: ['quality', 'cost', 'delivery'],
  },
  [FrameworkType.FISHBONE]: {
    type: FrameworkType.FISHBONE,
    icon: '骨',
    label: '特性要因図',
    description: '問題の原因を人・方法・設備・情報で整理する',
    category: '品質・論理',
    visualization: 'tree',
    nodeRoles: ['fishbone_root', 'fishbone_man', 'fishbone_machine', 'fishbone_material', 'fishbone_method', 'fishbone_leaf'],
  },
  [FrameworkType.ISSUE_TREE]: {
    type: FrameworkType.ISSUE_TREE,
    icon: '❓',
    label: 'イシューツリー',
    description: '答えるべき問いを階層的に分解する',
    category: '品質・論理',
    visualization: 'tree',
    nodeRoles: ['issue_root', 'issue_branch', 'issue_leaf'],
  },
  [FrameworkType.STP]: {
    type: FrameworkType.STP,
    icon: 'STP',
    label: 'STP分析',
    description: 'セグメンテーション・ターゲティング・ポジショニング',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['segmentation', 'targeting', 'positioning'],
  },
  [FrameworkType.PPM]: {
    type: FrameworkType.PPM,
    icon: 'PPM',
    label: 'PPM分析',
    description: '市場成長率×市場シェアで事業を分類する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['star', 'cash_cow', 'question_mark', 'dog'],
  },
  [FrameworkType.BSC]: {
    type: FrameworkType.BSC,
    icon: 'BSC',
    label: 'BSC（バランススコアカード）',
    description: '財務・顧客・内部プロセス・学習と成長の4視点で評価する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['bsc_financial', 'bsc_customer', 'bsc_process', 'bsc_learning'],
  },
  [FrameworkType.KPI]: {
    type: FrameworkType.KPI,
    icon: 'KPI',
    label: 'KPI分析',
    description: 'KGIからKPIへ目標を階層的に分解する',
    category: '戦略分析',
    visualization: 'tree',
    nodeRoles: ['kgi', 'kpi', 'kpi_action'],
  },
  [FrameworkType.ABC]: {
    type: FrameworkType.ABC,
    icon: 'ABC',
    label: 'ABC分析',
    description: '活動基準でコストと収益性のバランスを分析する',
    category: '戦略分析',
    visualization: 'matrix',
    nodeRoles: ['abc_high', 'abc_mid', 'abc_low'],
  },
  [FrameworkType.RACI]: {
    type: FrameworkType.RACI,
    icon: 'RACI',
    label: 'RACIチャート',
    description: '実行・説明責任・相談先・報告先で役割を明確にする',
    category: 'プロジェクト管理',
    visualization: 'matrix',
    nodeRoles: ['raci_responsible', 'raci_accountable', 'raci_consulted', 'raci_informed'],
  },
  [FrameworkType.WBS]: {
    type: FrameworkType.WBS,
    icon: 'WBS',
    label: 'WBS',
    description: 'プロジェクトの作業を階層的に分解する',
    category: 'プロジェクト管理',
    visualization: 'tree',
    nodeRoles: ['wbs_root', 'wbs_phase', 'wbs_task', 'wbs_subtask'],
  },
  [FrameworkType.YWT]: {
    type: FrameworkType.YWT,
    icon: 'YWT',
    label: 'YWT振り返り',
    description: 'やったこと・わかったこと・次にやることで振り返る',
    category: '論理構造',
    visualization: 'matrix',
    nodeRoles: ['did', 'learned', 'next'],
  },
  [FrameworkType.SPIN]: {
    type: FrameworkType.SPIN,
    icon: 'SPIN',
    label: 'SPIN話法',
    description: '状況・問題・示唆・解決でニーズを引き出す',
    category: '業務改善',
    visualization: 'matrix',
    nodeRoles: ['spin_situation', 'spin_problem', 'spin_implication', 'spin_need'],
  },
  [FrameworkType.CUSTOMER_JOURNEY]: {
    type: FrameworkType.CUSTOMER_JOURNEY,
    icon: '🧭',
    label: 'カスタマージャーニーマップ',
    description: '顧客の認知から購入・定着までの行動・思考・感情を可視化する',
    category: '業務改善',
    visualization: 'matrix',
    nodeRoles: ['cj_awareness', 'cj_consideration', 'cj_purchase', 'cj_retention', 'cj_advocacy'],
  },
  [FrameworkType.VSM]: {
    type: FrameworkType.VSM,
    icon: '🗺️',
    label: 'バリューストリームマッピング',
    description: '価値の流れを可視化し無駄・ボトルネックを特定する',
    category: '業務改善',
    visualization: 'matrix',
    nodeRoles: ['vsm_input', 'vsm_value_add', 'vsm_non_value', 'vsm_output', 'vsm_bottleneck'],
  },
  [FrameworkType.DMAIC]: {
    type: FrameworkType.DMAIC,
    icon: 'DMAIC',
    label: 'DMAIC（シックスシグマ）',
    description: '定義・測定・分析・改善・管理の5ステップで品質改善する',
    category: '品質・論理',
    visualization: 'matrix',
    nodeRoles: ['dmaic_define', 'dmaic_measure', 'dmaic_analyze', 'dmaic_improve', 'dmaic_control'],
  },
}
